export const CHANGE_ACTIVEID = 'CHANGE_ACTIVEID';
export const CHANGE_VIEWMODE = 'CHANGE_VIEWMODE';
export const SAVE_POSTCONTENTS = 'SAVE_POSTCONTENTS';
export const LOAD_POST_CONTENTS = 'LOAD_POST_CONTENTS';
export const LOAD_TEMPPOST_CONTENTS = 'LOAD_TEMPPOST_CONTENTS';
export const LOAD_POST_TOC = 'LOAD_POST_TOC';